// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNlZTip_wYT1iF-Yf_iw18sVK6Cn_qAlY',
    appId: '1:1012122600607:web:d4cc2d03fd6a73d1294eaa',
    messagingSenderId: '1012122600607',
    projectId: 'tripplanner-840ea',
    authDomain: 'tripplanner-840ea.firebaseapp.com',
    storageBucket: 'tripplanner-840ea.appspot.com',
    measurementId: 'G-28E2MJM678',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbXOEkxkn_7CkJFcmowXAYJ9FZiHbbkQc',
    appId: '1:1012122600607:android:dd9078b681187ea0294eaa',
    messagingSenderId: '1012122600607',
    projectId: 'tripplanner-840ea',
    storageBucket: 'tripplanner-840ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2E-s-cpeZnZZQjlbdvVE7_j3h0rbAWnw',
    appId: '1:1012122600607:ios:53f8e4d0f5717038294eaa',
    messagingSenderId: '1012122600607',
    projectId: 'tripplanner-840ea',
    storageBucket: 'tripplanner-840ea.appspot.com',
    iosBundleId: 'com.example.tripPlanner360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2E-s-cpeZnZZQjlbdvVE7_j3h0rbAWnw',
    appId: '1:1012122600607:ios:53f8e4d0f5717038294eaa',
    messagingSenderId: '1012122600607',
    projectId: 'tripplanner-840ea',
    storageBucket: 'tripplanner-840ea.appspot.com',
    iosBundleId: 'com.example.tripPlanner360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNlZTip_wYT1iF-Yf_iw18sVK6Cn_qAlY',
    appId: '1:1012122600607:web:3af8ee0f38b1eb76294eaa',
    messagingSenderId: '1012122600607',
    projectId: 'tripplanner-840ea',
    authDomain: 'tripplanner-840ea.firebaseapp.com',
    storageBucket: 'tripplanner-840ea.appspot.com',
    measurementId: 'G-64LYT5VV5J',
  );

}